title: IG Comparator | whdzera
email: whdzera@gmail.com
baseurl: "/ig-comparator"
url: "" 
twitter_username: whdzera
github_username:  rokhimin/ig-comparator

permalink: /:title.rb
files: "/ig-comparator"
